version: '3'
services:
  zookeeper:
    #image: wurstmeister/zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.4
      KAFKA_CREATE_TOPICS: "qqmsg:3:1:delete,qqpush:3:1:delete"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_SEGMENT_MS: 86400000
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000
      KAFKA_LOG_RETENTION_HOURS: 1
    volumes:
      - /run/docker.sock:/var/run/docker.sock

  kafka-manager:
#    image: sheepkiller/kafka-manager
    image: scjtqs/kafka-manager:test
    restart: always
    depends_on: [ zookeeper ]
    ports:
      - "9093:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
#      APPLICATION_SECRET: scjtqs
#      KM_ARGS: -Djava.net.preferIPv4Stack=true
